#******************************************************************************
# The MIT License (MIT)
#  
# Copyright (c) 2015 Neustar Inc.
#  
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#  
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#  
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#******************************************************************************
#
# $Id: Makefile,v 1.2 2006/03/01 01:35:37 wtan Exp $
#
# This is the Makefile for building EPP C++ Implementation
#
# Makefile for directory src/cn

TOP=../..
DIRS=
include $(TOP)/src/Makefile.plat

OBJS=\
	CNContact.$(O)	\
	CNContactCreateExt.$(O)	\
	CNContactInfoExt.$(O)	\
	CNContactUpdateExt.$(O)	\
	CNDomain.$(O)	\
	CNDomainCreateExt.$(O)	\
	CNDomainInfoExt.$(O)	\
	CNDomainUpdateExt.$(O)	\
	CNHostCreateExt.$(O)	\
	CNHostInfoExt.$(O)	\
	CNHostUpdateExt.$(O)	\
	CNCDNExt.$(O)	\

HDRS=\
	CNContact.hpp	\
	CNContactCreateExt.hpp	\
	CNContactInfoExt.hpp	\
	CNContactUpdateExt.hpp	\
	CNDomain.hpp	\
	CNDomainCreateExt.hpp	\
	CNDomainInfoExt.hpp	\
	CNDomainUpdateExt.hpp	\
	CNHostCreateExt.hpp	\
	CNHostInfoExt.hpp	\
	CNHostUpdateExt.hpp	\
	CNCDNExt.hpp	\

SRCS=\
	CNContact.cpp	\
	CNContactCreateExt.cpp	\
	CNContactInfoExt.cpp	\
	CNContactUpdateExt.cpp	\
	CNDomain.cpp	\
	CNDomainCreateExt.cpp	\
	CNDomainInfoExt.cpp	\
	CNDomainUpdateExt.cpp	\
	CNHostCreateExt.cpp	\
	CNHostInfoExt.cpp	\
	CNHostUpdateExt.cpp	\
	CNCDNExt.cpp	\


TARGETS=$(OBJS)
include $(TOP)/src/Makefile.incl
